# Generated by Django 4.2.7 on 2024-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Static/')),
                ('location', models.TextField()),
            ],
        ),
    ]
