# Generated by Django 4.2.7 on 2024-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0003_alter_profile_det_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_det',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
