# Generated by Django 4.2.7 on 2024-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0005_alter_profile_det_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='terms',
            field=models.BooleanField(default=0, null=0),
            preserve_default=False,
        ),
    ]
