# Generated by Django 4.2.7 on 2024-06-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0007_alter_details_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='terms',
            field=models.CharField(max_length=10),
        ),
    ]
