# Generated by Django 4.2.7 on 2024-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0009_alter_profile_det_avatar_alter_profile_det_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='avatar',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
