# Generated by Django 4.2.7 on 2024-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0010_details_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_det',
        ),
        migrations.AddField(
            model_name='details',
            name='location',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
    ]
