# Generated by Django 4.2.7 on 2024-06-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribble', '0012_profile_det'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_det',
        ),
    ]
